(function(){
  'use strict';
  const KEY='clubgest_access_v1';
  const ACC=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}};
  const save=a=>localStorage.setItem(KEY,JSON.stringify(a));
  const roleNames={parent:'👨‍👩‍👧 Encarregado',player:'🧒 Jogador',coach:'⚽ Coach',admin:'🛠 Admin'};
  let selected=localStorage.getItem('cgRole')||'';
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function addCss(){const s=document.createElement('style');s.textContent=`
  .cg-access{position:fixed;inset:0;background:rgba(15,23,42,.82);backdrop-filter:blur(12px);z-index:9999;display:flex;align-items:center;justify-content:center;padding:14px}
  .cg-sheet{width:min(720px,100%);max-height:94vh;overflow:auto;background:#fff;border-radius:28px;padding:24px;box-shadow:0 30px 90px #0007}
  .cg-brand{display:flex;align-items:center;gap:10px;margin-bottom:14px}.cg-crest{width:46px;height:46px;border-radius:14px;background:linear-gradient(145deg,#c8102e,#7f0b1d);display:grid;place-items:center;color:#fff;font-size:22px}.cg-kicker{font-size:9px;letter-spacing:.15em;font-weight:900;color:#98a2b3}.cg-sheet h2{margin:5px 0;font-size:26px}.cg-sub{margin:0 0 16px;color:#667085;font-size:12px}.cg-roles{display:grid;grid-template-columns:1fr 1fr;gap:10px}.cg-role{border:1px solid #e7e9ee;border-radius:17px;padding:14px;text-align:left;background:#fff}.cg-role.active{border-color:#c8102e;background:#fff5f6;box-shadow:0 0 0 2px #c8102e14}.cg-role b{display:block;font-size:14px}.cg-role span{display:block;margin-top:4px;color:#667085;font-size:10px;line-height:1.4}.cg-form{margin-top:14px;padding:14px;border:1px solid #e7e9ee;border-radius:17px;background:#f8fafc;display:grid;gap:9px}.cg-form label{font-size:10px;font-weight:800;color:#475467}.cg-form input,.cg-form select{width:100%;padding:11px;border:1px solid #dfe3e8;border-radius:11px;background:#fff}.cg-hint{font-size:10px;color:#667085;line-height:1.45}.cg-error{color:#b42336;background:#fdebed;padding:9px;border-radius:10px;font-size:10px;font-weight:700}.cg-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:14px}.cg-btn{padding:11px 14px;border-radius:11px;border:0;font-weight:800}.cg-btn.light{background:#f2f4f7;color:#101828}.cg-btn.red{background:#c8102e;color:#fff}.cg-btn:disabled{opacity:.45;cursor:not-allowed}.cg-badge{padding:8px 10px;border-radius:999px;background:#111827;color:#fff;font-size:10px;font-weight:800;cursor:pointer;border:0}
  @media(max-width:600px){.cg-roles{grid-template-columns:1fr}.cg-sheet{padding:18px;border-radius:22px}.cg-actions{flex-direction:column}.cg-btn{width:100%}}
  `;document.head.appendChild(s)}
  function ensureTop(){const r=document.getElementById('role');if(!r)return;r.style.display='none';const host=r.parentElement;if(!document.getElementById('cg-profile')){const b=document.createElement('button');b.id='cg-profile';b.className='cg-badge';b.onclick=()=>show(true);host.appendChild(b)}updateTop()}
  function updateTop(){const b=document.getElementById('cg-profile');if(b)b.textContent='Perfil: '+(roleNames[selected]||'Escolher perfil')}
  function validUser(role,u){if(role==='coach')return /^C\d+U(7|9|11)$/i.test(u);if(role==='admin')return /^A\d+$/i.test(u);return true}
  function show(reselect){selected=reselect?'':(localStorage.getItem('cgRole')||'');render()}
  function render(err){const a=ACC();const existing=selected&&Object.values(a).find(x=>x&&x.role===selected&&x.user===localStorage.getItem('cgUser'));document.getElementById('cg-access')?.remove();const wrap=document.createElement('div');wrap.id='cg-access';wrap.className='cg-access';let roleCards=Object.keys(roleNames).map(r=>`<button type="button" class="cg-role ${selected===r?'active':''}" onclick="window.cgPick('${r}')"><b>${roleNames[r]}</b><span>${r==='parent'?'Acompanha filhos, treinos, jogos e presenças.':r==='player'?'Consulta equipa, agenda e atividades.':r==='coach'?'Gere uma equipa, jogadores e presenças.':'Gere o clube, equipas e visão global.'}</span></button>`).join('');let form='';if(selected==='coach'){form=`<div class="cg-form"><label>Username do coach<input id="cg-user" value="${esc(existing?.user||'C1U7')}" placeholder="C1U7" autocomplete="username"></label><label>Equipa<select id="cg-team">${['U7','U9','U11'].map(x=>`<option ${existing?.team===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Código / password<input id="cg-code" type="password" placeholder="Escolhe qualquer código" autocomplete="current-password"></label><div class="cg-hint">Formato: <b>C1U7</b>, <b>C2U7</b>, <b>C1U9</b>, <b>C1U11</b>. O código pode ser definido pelo coach.</div>${err?`<div class="cg-error">${esc(err)}</div>`:''}</div>`}else if(selected==='admin'){form=`<div class="cg-form"><label>Username de admin<input id="cg-user" value="${esc(existing?.user||'A1')}" placeholder="A1" autocomplete="username"></label><label>Código / password<input id="cg-code" type="password" placeholder="Escolhe qualquer código" autocomplete="current-password"></label><div class="cg-hint">Formato: <b>A1</b>, <b>A2</b>, <b>A3</b>… O código pode ser definido pelo admin.</div>${err?`<div class="cg-error">${esc(err)}</div>`:''}</div>`}else if(selected){form=`<div class="cg-form"><div class="cg-hint"><b>${roleNames[selected]}</b> não precisa de código. Continua para entrar no ClubGest.</div></div>`}wrap.innerHTML=`<div class="cg-sheet"><div class="cg-brand"><div class="cg-crest">⚽</div><div><span class="cg-kicker">BEM-VINDO AO CLUBGEST</span><h2>Quem és?</h2></div></div><p class="cg-sub">Escolhe o teu perfil para veres as opções certas para ti.</p><div class="cg-roles">${roleCards}</div>${form}<div class="cg-actions"><button class="cg-btn light" onclick="window.cgClose()">Cancelar</button><button class="cg-btn red" onclick="window.cgContinue()" ${selected?'':'disabled'}>Continuar</button></div></div>`;document.body.appendChild(wrap)}
  window.cgPick=r=>{selected=r;render()};
  window.cgClose=()=>{if(localStorage.getItem('cgRole'))document.getElementById('cg-access')?.remove()};
  window.cgContinue=()=>{if(!selected)return;const a=ACC();if(selected==='parent'||selected==='player'){localStorage.setItem('cgRole',selected);localStorage.setItem('cgOnboarded','1');document.getElementById('cg-access')?.remove();updateTop();if(typeof window.render==='function')window.render();return}const u=(document.getElementById('cg-user')?.value||'').trim().toUpperCase();const c=document.getElementById('cg-code')?.value||'';if(!validUser(selected,u)){render('Username inválido. Usa o formato '+(selected==='coach'?'C1U7 / C2U7 / C1U9 / C1U11.':'A1 / A2 / A3…'));return}if(!c){render('Introduz um código. Na primeira vez, esse código fica associado ao username.');return}const key=selected+':'+u;const old=a[key];if(old&&old.code!==c){render('Código incorreto para este username.');return}a[key]={role:selected,user:u,code:c,team:document.getElementById('cg-team')?.value||old?.team||'U9',createdAt:old?.createdAt||new Date().toISOString()};save(a);localStorage.setItem('cgRole',selected);localStorage.setItem('cgUser',u);localStorage.setItem('cgTeam',a[key].team);localStorage.setItem('cgOnboarded','1');document.getElementById('cg-access')?.remove();updateTop();if(typeof window.render==='function')window.render()};
  function boot(){addCss();ensureTop();if(localStorage.getItem('cgOnboarded')!=='1')show(false);else updateTop()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
