(function(){
'use strict';
const KEY='clubgest_access_v2';
const SB_URL='https://zdgcxbcsnlwrzhtlklih.supabase.co';
const SB_KEY='sb_publishable_tchykrPPHUj9Yu8kxM6Xxg_u-y6_Us9';
const roles={parent:'👨‍👩‍👧 Encarregado',player:'🧒 Jogador',coach:'⚽ Coach',admin:'🛠 Admin'};
let selected=localStorage.getItem('cgRole')||'';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function state(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}}
function setState(v){localStorage.setItem(KEY,JSON.stringify(v))}
async function rpc(fn,body){const r=await fetch(SB_URL+'/rest/v1/rpc/'+fn,{method:'POST',headers:{'Content-Type':'application/json','apikey':SB_KEY,'Authorization':'Bearer '+SB_KEY},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||j.error||'Falha de ligação');return j}
function css(){if(document.getElementById('cg-access-css'))return;const s=document.createElement('style');s.id='cg-access-css';s.textContent=`
.cg-access{position:fixed;inset:0;background:linear-gradient(135deg,rgba(5,5,7,.94),rgba(30,0,4,.88));backdrop-filter:blur(14px);z-index:9999;display:flex;align-items:center;justify-content:center;padding:14px}.cg-sheet{width:min(720px,100%);max-height:94vh;overflow:auto;background:#fff;border:1px solid #eee;border-radius:28px;padding:24px;box-shadow:0 30px 100px #0008}.cg-brand{display:flex;align-items:center;gap:12px;margin-bottom:16px}.cg-logo{width:56px;height:56px;border-radius:16px;object-fit:contain;background:#080808;padding:5px}.cg-kicker{font-size:9px;letter-spacing:.16em;font-weight:900;color:#8b8b8b}.cg-sheet h2{margin:4px 0;font-size:27px}.cg-sub{margin:0 0 16px;color:#667085;font-size:12px}.cg-roles{display:grid;grid-template-columns:1fr 1fr;gap:10px}.cg-role{border:1px solid #e7e9ee;border-radius:17px;padding:14px;text-align:left;background:#fff}.cg-role.active{border-color:#fd0200;background:#fff4f4;box-shadow:0 0 0 2px #fd020018}.cg-role b{display:block;font-size:14px}.cg-role span{display:block;margin-top:4px;color:#667085;font-size:10px;line-height:1.4}.cg-form{margin-top:14px;padding:14px;border:1px solid #e7e9ee;border-radius:17px;background:#f8fafc;display:grid;gap:9px}.cg-form label{font-size:10px;font-weight:800;color:#475467}.cg-form input,.cg-form select{width:100%;padding:11px;border:1px solid #dfe3e8;border-radius:11px;background:#fff}.cg-hint{font-size:10px;color:#667085;line-height:1.45}.cg-error{color:#b42336;background:#fdebed;padding:9px;border-radius:10px;font-size:10px;font-weight:700}.cg-pending{color:#9a3412;background:#fff7ed;padding:11px;border-radius:12px;font-size:11px;line-height:1.45}.cg-ok{color:#166534;background:#ecfdf3;padding:11px;border-radius:12px;font-size:11px;line-height:1.45}.cg-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:14px}.cg-btn{padding:11px 14px;border-radius:11px;border:0;font-weight:800}.cg-btn.light{background:#f2f4f7;color:#101828}.cg-btn.red{background:#fd0200;color:#fff}.cg-btn:disabled{opacity:.45;cursor:not-allowed}.cg-badge{padding:8px 10px;border-radius:999px;background:#080808;color:#fff;font-size:10px;font-weight:800;cursor:pointer;border:0}.cg-a1{background:#111;color:#fff;border-radius:15px;padding:13px;font-size:11px}.cg-a1 b{color:#ff3030}@media(max-width:600px){.cg-roles{grid-template-columns:1fr}.cg-sheet{padding:18px;border-radius:22px}.cg-actions{flex-direction:column}.cg-btn{width:100%}}
`;document.head.appendChild(s)}
function top(){const r=document.getElementById('role');if(!r)return;r.style.display='none';const host=r.parentElement;if(!document.getElementById('cg-profile')){const b=document.createElement('button');b.id='cg-profile';b.className='cg-badge';b.onclick=()=>show(true);host.appendChild(b)}const role=localStorage.getItem('cgRole')||'';document.getElementById('cg-profile').textContent='Perfil: '+(roles[role]||'Escolher perfil')}
function valid(role,u){return role==='coach'?/^C\d+U(7|9|11)$/i.test(u):role==='admin'?/^A\d+$/i.test(u):true}
function show(reselect,msg){selected=reselect?'':(localStorage.getItem('cgRole')||'');document.getElementById('cg-access')?.remove();const w=document.createElement('div');w.id='cg-access';w.className='cg-access';let cards=Object.keys(roles).map(r=>`<button type="button" class="cg-role ${selected===r?'active':''}" onclick="window.cgPick('${r}')"><b>${roles[r]}</b><span>${r==='parent'?'Acompanha o jogador, agenda, jogos e presenças.':r==='player'?'Consulta equipa, agenda e atividades.':r==='coach'?'Acesso profissional à equipa após aprovação do A1.':'Administração do clube; A1 controla aprovações.'}</span></button>`).join('');let form='';if(selected==='coach')form=`<div class="cg-form"><label>Username<input id="cg-user" value="C1U7" placeholder="C1U7" autocomplete="username"></label><label>Equipa<select id="cg-team"><option>U7</option><option>U9</option><option>U11</option></select></label><label>Código<input id="cg-code" type="password" placeholder="O teu código" autocomplete="current-password"></label><div class="cg-hint">Formato obrigatório: <b>C1U7</b>, <b>C2U7</b>, <b>C1U9</b>, <b>C1U11</b>… O coach escolhe o próprio código.</div>${msg||''}</div>`;else if(selected==='admin')form=`<div class="cg-form"><label>Username<input id="cg-user" value="A2" placeholder="A2" autocomplete="username"></label><label>Código<input id="cg-code" type="password" placeholder="O teu código" autocomplete="current-password"></label><div class="cg-hint">Formato: <b>A2</b>, <b>A3</b>… O <b>A1 é o Admin Geral</b> e aprova a entrada de novos admins e coaches.</div>${msg||''}</div>`;else if(selected)form=`<div class="cg-form"><div class="cg-hint"><b>${roles[selected]}</b> não precisa de código.</div></div>`;w.innerHTML=`<div class="cg-sheet"><div class="cg-brand"><img class="cg-logo" src="https://upload.wikimedia.org/wikipedia/commons/8/8b/Logo_fcd_grand.svg" onerror="this.style.display='none'"><div><span class="cg-kicker">FC DÉIFFERDENG 03 · CLUBGEST</span><h2>Quem és?</h2></div></div><p class="cg-sub">Uma experiência ClubGest feita à medida do FCD03.</p><div class="cg-roles">${cards}</div>${form}<div class="cg-actions"><button class="cg-btn light" onclick="window.cgClose()">Cancelar</button><button class="cg-btn red" onclick="window.cgContinue()" ${selected?'':'disabled'}>Continuar</button></div></div>`;document.body.appendChild(w)}
window.cgPick=r=>{selected=r;show(false)};
window.cgClose=()=>{if(localStorage.getItem('cgRole'))document.getElementById('cg-access')?.remove()};
window.cgContinue=async()=>{if(!selected)return;if(selected==='parent'||selected==='player'){localStorage.setItem('cgRole',selected);localStorage.setItem('cgOnboarded','1');document.getElementById('cg-access')?.remove();top();if(window.render)window.render();return}
const u=(document.getElementById('cg-user')?.value||'').trim().toUpperCase(), c=document.getElementById('cg-code')?.value||'', team=document.getElementById('cg-team')?.value||null;
if(!valid(selected,u)){show(false,`<div class="cg-error">Username inválido. Usa ${selected==='coach'?'C1U7 / C2U7 / C1U9 / C1U11':'A2 / A3 / A4…'}</div>`);return}if(!c){show(false,'<div class="cg-error">Introduz o teu código.</div>');return}
try{if(selected==='admin'&&u==='A1'){show(false,'<div class="cg-a1"><b>A1 · ADMIN GERAL</b><br>O A1 é uma conta protegida. A ativação final será ligada à autenticação segura do Supabase; não é criada por auto-registo.</div>');return}
const key=selected+':'+u;const old=state()[key];let result;if(old?.status==='approved'){result=await rpc('check_access',{p_username:u,p_role:selected,p_code:c})}else{result=await rpc('request_access',{p_username:u,p_role:selected,p_team:team,p_code:c})}
if(result.status==='pending'){const a=state();a[key]={role:selected,user:u,team:team,status:'pending',createdAt:old?.createdAt||new Date().toISOString()};setState(a);show(false,'<div class="cg-pending"><b>Pedido enviado.</b><br>O A1 — Admin Geral — tem de aprovar esta entrada. Volta a entrar com o mesmo username e código depois da aprovação.</div>');return}
if(result.status==='rejected'){show(false,'<div class="cg-error">Este pedido foi rejeitado pelo A1.</div>');return}
if(result.status==='approved'){const a=state();a[key]={role:selected,user:u,team:result.team||team,status:'approved',createdAt:old?.createdAt||new Date().toISOString()};setState(a);localStorage.setItem('cgRole',selected);localStorage.setItem('cgUser',u);localStorage.setItem('cgTeam',result.team||team||'U9');localStorage.setItem('cgOnboarded','1');document.getElementById('cg-access')?.remove();top();if(window.render)window.render();return}
show(false,'<div class="cg-error">Não foi possível validar o acesso. Tenta novamente.</div>')}catch(e){show(false,'<div class="cg-error">Sem ligação ao servidor. O pedido não foi perdido; tenta novamente quando houver ligação.</div>')}};
function boot(){css();top();if(localStorage.getItem('cgOnboarded')!=='1')show(false)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
