(function(){
'use strict';
const KEY='clubgest_v3';
function role(){return localStorage.getItem('cgRole')||'parent'}
function isAdmin(){return role()==='admin'}
function state(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){return null}}
function save(d){localStorage.setItem(KEY,JSON.stringify(d));if(typeof window.render==='function')window.render()}
function esc(v){return String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[m]))}
function teams(d){return Object.keys((d&&d.teams)||{}).map(k=>d.teams[k]).filter(Boolean)}
function teamKeys(d){return Object.keys((d&&d.teams)||{})}
function selectedKey(d){return d&&d.selected&&d.teams&&d.teams[d.selected]?d.selected:teamKeys(d)[0]}
function ensure(d){if(!d.teams)d.teams={};if(!Array.isArray(d.coaches))d.coaches=[];Object.keys(d.teams).forEach(k=>{if(!Array.isArray(d.teams[k].players))d.teams[k].players=[]});return d}
function toast(msg){if(typeof window.toast==='function'){window.toast(msg);return}const el=document.getElementById('toast');if(!el)return;el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function addTeam(){const n=(document.getElementById('adm-team-name')?.value||'').trim(),s=(document.getElementById('adm-team-season')?.value||'').trim()||'2026/2027';if(!n)return toast('Indique o nome da equipa.');const d=ensure(state()||{}),key=n.toUpperCase().replace(/\s+/g,' ').replace(/[^A-Z0-9À-ÿ _-]/gi,'').replace(/\s/g,'');if(!key)return toast('Nome de equipa inválido.');if(d.teams[key])return toast('Essa equipa já existe.');d.teams[key]={name:n,season:s,coach:'',players:[]};d.selected=key;save(d);localStorage.setItem('cgViewTeam',key);toast('Equipa adicionada ✓');render()}
function addPlayer(){const d=ensure(state()||{}),k=document.getElementById('adm-player-team')?.value||selectedKey(d),n=(document.getElementById('adm-player-name')?.value||'').trim(),b=document.getElementById('adm-player-birth')?.value||'',p=(document.getElementById('adm-player-pos')?.value||'').trim()||'Jogador';if(!d.teams[k]||!n)return toast('Indique a equipa e o nome.');d.teams[k].players.push({name:n,birth:b,pos:p});d.selected=k;save(d);toast('Jogador adicionado ✓');render()}
function addCoach(){const d=ensure(state()||{}),n=(document.getElementById('adm-coach-name')?.value||'').trim(),u=(document.getElementById('adm-coach-user')?.value||'').trim().toUpperCase(),k=document.getElementById('adm-coach-team')?.value||'';if(!n||!u||!k)return toast('Preencha nome, username e equipa.');if(!/^C\d+U[A-Z0-9]+$/i.test(u))return toast('Username de coach inválido.');const exists=d.coaches.some(c=>c.username===u);if(exists)return toast('Esse coach já existe.');d.coaches.push({name:n,username:u,team:k,status:'active'});if(d.teams[k]&&!d.teams[k].coach)d.teams[k].coach=n;save(d);toast('Coach adicionado ✓');render()}
function removePlayer(k,i){if(!confirm('Remover este jogador?'))return;const d=ensure(state()||{});if(d.teams[k])d.teams[k].players.splice(i,1);save(d);render()}
function removeCoach(i){if(!confirm('Remover este coach da gestão?'))return;const d=ensure(state()||{});d.coaches.splice(i,1);save(d);render()}
function render(){if(!isAdmin())return;const box=document.getElementById('cg-admin-panel');if(!box)return;const d=ensure(state()||{}),keys=teamKeys(d),current=selectedKey(d);let total=0;keys.forEach(k=>total+=(d.teams[k].players||[]).length);const coachCount=d.coaches.length;box.innerHTML=`<div class="cg-admin-head"><div><span class="kicker">ADMINISTRAÇÃO DO CLUBE</span><h2>Centro de gestão</h2><p>O Admin cria as equipas e depois controla jogadores, coaches e composição de cada grupo.</p></div><span class="badge dark">${keys.length} equipas</span></div>
<div class="cg-admin-stats"><div><small>Equipas</small><strong>${keys.length}</strong></div><div><small>Jogadores</small><strong>${total}</strong></div><div><small>Coaches</small><strong>${coachCount}</strong></div></div>
<div class="cg-admin-section"><div class="head"><div><h3>Equipas</h3><p>Crie uma nova equipa e escolha-a para gerir tudo.</p></div></div><div class="cg-admin-form"><input id="adm-team-name" placeholder="Nome da equipa · ex. U13"><input id="adm-team-season" placeholder="Época · ex. 2026/2027"><button class="btn red" id="adm-team-add">+ Nova equipa</button></div><div class="cg-admin-team-grid">${keys.map(k=>`<button class="cg-admin-team ${k===current?'active':''}" data-team="${esc(k)}"><b>${esc(d.teams[k].name||k)}</b><small>${esc(d.teams[k].season||'')} · ${(d.teams[k].players||[]).length} jogadores</small></button>`).join('')}</div></div>
<div class="cg-admin-section"><div class="head"><div><h3>Adicionar jogadores</h3><p>Escolha a equipa e introduza os jogadores.</p></div></div><div class="cg-admin-form cg-player-form"><select id="adm-player-team">${keys.map(k=>`<option value="${esc(k)}" ${k===current?'selected':''}>${esc(d.teams[k].name||k)}</option>`).join('')}</select><input id="adm-player-name" placeholder="Nome completo"><input id="adm-player-birth" type="date"><input id="adm-player-pos" placeholder="Posição"><button class="btn" id="adm-player-add">+ Adicionar jogador</button></div><div class="cg-admin-list">${current&&d.teams[current]&&(d.teams[current].players||[]).length?(d.teams[current].players||[]).map((p,i)=>`<div class="row"><div class="left"><div class="avatar">${esc((p.name||'?').slice(0,1).toUpperCase())}</div><div><strong>${esc(p.name)}</strong><span class="muted">${esc(p.pos||'Jogador')}${p.birth?' · '+esc(p.birth):''}</span></div></div><button class="btn light small" data-remove-player="${i}">Remover</button></div>`).join(''):'<div class="empty">Ainda não há jogadores nesta equipa.</div>'}</div></div>
<div class="cg-admin-section"><div class="head"><div><h3>Adicionar coaches</h3><p>Associe cada coach a uma equipa.</p></div></div><div class="cg-admin-form"><input id="adm-coach-name" placeholder="Nome do coach"><input id="adm-coach-user" placeholder="Username · ex. C1U7"><select id="adm-coach-team">${keys.map(k=>`<option value="${esc(k)}">${esc(d.teams[k].name||k)}</option>`).join('')}</select><button class="btn" id="adm-coach-add">+ Adicionar coach</button></div><div class="cg-admin-list">${coachCount?d.coaches.map((c,i)=>`<div class="row"><div class="left"><div class="avatar">⚽</div><div><strong>${esc(c.name)}</strong><span class="muted">${esc(c.username)} · ${esc(c.team)}</span></div></div><button class="btn light small" data-remove-coach="${i}">Remover</button></div>`).join(''):'<div class="empty">Ainda não há coaches adicionados.</div>'}</div></div>`;
box.querySelector('#adm-team-add').onclick=addTeam;box.querySelector('#adm-player-add').onclick=addPlayer;box.querySelector('#adm-coach-add').onclick=addCoach;box.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>{const x=state();if(x&&x.teams[b.dataset.team]){x.selected=b.dataset.team;localStorage.setItem(KEY,JSON.stringify(x));localStorage.setItem('cgViewTeam',b.dataset.team);if(window.ClubGestTeamView)window.ClubGestTeamView.refresh();if(typeof window.render==='function')window.render();render()}});box.querySelectorAll('[data-remove-player]').forEach(b=>b.onclick=()=>removePlayer(current,Number(b.dataset.removePlayer)));box.querySelectorAll('[data-remove-coach]').forEach(b=>b.onclick=()=>removeCoach(Number(b.dataset.removeCoach)))}
function mount(){if(!isAdmin())return;const manage=document.getElementById('manage');if(!manage)return;let box=document.getElementById('cg-admin-panel');if(!box){box=document.createElement('div');box.id='cg-admin-panel';box.className='cg-admin-panel';manage.prepend(box)}render()}
function css(){if(document.getElementById('cg-admin-css'))return;const s=document.createElement('style');s.id='cg-admin-css';s.textContent='.cg-admin-panel{margin-top:14px}.cg-admin-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;background:#111827;color:#fff;border-radius:22px;padding:18px}.cg-admin-head h2{margin:4px 0;font-size:22px}.cg-admin-head p{margin:0;color:#cbd0d8;font-size:11px;max-width:650px}.cg-admin-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:10px}.cg-admin-stats div{background:#fff;border:1px solid #e7e9ee;border-radius:16px;padding:13px}.cg-admin-stats small{color:#667085}.cg-admin-stats strong{display:block;font-size:24px;margin-top:3px}.cg-admin-section{margin-top:12px;background:#fff;border:1px solid #e7e9ee;border-radius:20px;padding:15px}.cg-admin-form{display:grid;grid-template-columns:1fr 1fr auto;gap:8px;margin-bottom:10px}.cg-admin-form input,.cg-admin-form select{min-height:42px;border:1px solid #dfe3e8;border-radius:11px;padding:10px;background:#fff}.cg-player-form{grid-template-columns:1fr 1.4fr 1fr 1fr auto}.cg-admin-team-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.cg-admin-team{padding:11px;border:1px solid #e7e9ee;border-radius:14px;background:#fff;text-align:left}.cg-admin-team.active{border-color:#e30613;background:#fff5f5}.cg-admin-team b{display:block}.cg-admin-team small{display:block;color:#667085;margin-top:3px;font-size:10px}.cg-admin-list{display:grid;gap:8px}.cg-admin-list .row{margin-top:2px}@media(max-width:760px){.cg-admin-head{flex-direction:column}.cg-admin-stats{grid-template-columns:1fr 1fr 1fr}.cg-admin-form,.cg-player-form{grid-template-columns:1fr 1fr}.cg-admin-form .btn{grid-column:1/-1}.cg-admin-team-grid{grid-template-columns:1fr 1fr}}';document.head.appendChild(s)}
function refresh(){css();if(isAdmin())mount();else document.getElementById('cg-admin-panel')?.remove()}
function boot(){refresh();let pending=false;const obs=new MutationObserver(()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;refresh()})});obs.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('storage',refresh)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
window.ClubGestAdmin={refresh,addTeam,addPlayer,addCoach};
})();
