(function(){
'use strict';
const SB_URL='https://zdgcxbcsnlwrzhtlklih.supabase.co',SB_KEY='sb_publishable_tchykrPPHUj9Yu8kx6M6Xxg_u-y6_Us9'.replace('8M6','8kx6'),CLUB_ID='f7ba0680-d3b5-4064-8e6e-92ee4a85ccbf',LOCAL='clubgest_v3',CHAT_KEY='cgChatMessages';
function role(){return localStorage.getItem('cgRole')||'parent'}
function allowed(){return ['parent','coach','admin'].includes(role())}
function jwt(){try{const direct=localStorage.getItem('sb-access-token');if(direct)return direct;for(const k of Object.keys(localStorage)){if(!k.startsWith('sb-')||!k.endsWith('-auth-token'))continue;const raw=JSON.parse(localStorage.getItem(k)||'null');if(raw?.access_token)return raw.access_token}}catch(e){}return ''}
function uid(){const tok=jwt();try{return tok?JSON.parse(atob(tok.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))).sub:''}catch(e){return ''}}
function auth(){const tok=jwt();return tok?{apikey:SB_KEY,Authorization:'Bearer '+tok,'Content-Type':'application/json'}:{apikey:SB_KEY,Authorization:'Bearer '+SB_KEY,'Content-Type':'application/json'}}
async function api(path,opts){const r=await fetch(SB_URL+'/rest/v1/'+path,Object.assign({headers:auth()},opts||{}));if(!r.ok)throw new Error('chat '+r.status);return r.status===204?null:r.json()}
function state(){try{return JSON.parse(localStorage.getItem(LOCAL)||'{}')}catch(e){return{}}}
function saveState(s){try{localStorage.setItem(LOCAL,JSON.stringify(s))}catch(e){}}
function demoMessages(){const s=state();return Array.isArray(s[CHAT_KEY])?s[CHAT_KEY]:[]}
function setDemoMessages(m){const s=state();s[CHAT_KEY]=m.slice(-100);saveState(s)}
function roleLabel(){return role()==='admin'?'Administrador':role()==='coach'?'Treinador':'Encarregado'}
function senderName(){return (localStorage.getItem('cgChatName')||roleLabel()).trim().slice(0,120)}
function esc(v){return String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[m]))}
function isDemo(){return !uid()||localStorage.getItem('cgDemoMode')==='1'}
async function load(){if(isDemo())return demoMessages();try{return await api('chat_messages?select=id,sender_profile_id,sender_name,body,created_at&club_id=eq.'+CLUB_ID+'&order=created_at.asc&limit=100')}catch(e){return demoMessages()}}
async function send(body){const clean=String(body||'').trim();if(!clean)return;if(isDemo()){const m=demoMessages();m.push({id:'demo-'+Date.now(),sender_profile_id:uid()||role(),sender_name:senderName(),body:clean,created_at:new Date().toISOString()});setDemoMessages(m);return}await api('chat_messages',{method:'POST',headers:Object.assign(auth(),{Prefer:'return=minimal'}),body:JSON.stringify({club_id:CLUB_ID,sender_profile_id:uid(),sender_name:senderName(),body:clean})})}
function parentChildNames(){try{const a=JSON.parse(localStorage.getItem('cgParentChildren')||'[]');if(Array.isArray(a)&&a.length)return a.map(x=>x?.name).filter(Boolean)}catch(e){}const n=(localStorage.getItem('cgChildName')||'').trim();return n?[n]:[]}
function filterParentViews(){if(role()!=='parent')return;const names=parentChildNames(),d=state(),tm=d?.selected&&d?.teams?.[d.selected],own=new Set(names.map(x=>String(x).trim().toLowerCase()));if(tm){document.querySelectorAll('#attendance .row').forEach(row=>{const n=row.querySelector('.left strong')?.textContent?.trim().toLowerCase();if(n)row.style.display=own.has(n)?'':'none'});document.querySelectorAll('#team .player').forEach(row=>{const n=row.querySelector('.left strong')?.textContent?.trim().toLowerCase();if(n)row.style.display=own.has(n)?'':'none'});document.querySelectorAll('#home .grid').forEach(x=>x.style.display='none')}}
function renderBox(messages){const el=document.getElementById('cg-parent-chat');if(!el)return;const mine=uid();el.innerHTML='<div class="head"><div><h2>💬 Chat do clube</h2><p>Online · Encarregados, treinadores e administradores</p></div><span class="badge green">● Online</span></div><div class="cg-chat-list">'+(messages.length?messages.map(m=>'<div class="cg-chat-msg '+(mine&&m.sender_profile_id===mine?'mine':'')+'"><div><strong>'+esc(m.sender_name||'Membro do clube')+'</strong><span>'+esc(m.body)+'</span><small>'+new Intl.DateTimeFormat(localStorage.getItem('cgLang')||'pt',{hour:'2-digit',minute:'2-digit'}).format(new Date(m.created_at))+'</small></div></div>').join(''):'<div class="empty">Ainda não há mensagens. Envie a primeira pergunta.</div>')+'</div><form class="cg-chat-form" id="cg-chat-form"><input id="cg-chat-input" maxlength="2000" autocomplete="off" placeholder="Escreva uma pergunta ou mensagem…"><button class="btn red" type="submit">Enviar</button></form>';const list=el.querySelector('.cg-chat-list');list.scrollTop=list.scrollHeight;el.querySelector('#cg-chat-form').onsubmit=async e=>{e.preventDefault();const input=el.querySelector('#cg-chat-input'),v=input.value.trim();if(!v)return;input.disabled=true;try{await send(v);input.value='';await refresh()}catch(err){if(typeof window.toast==='function')window.toast('Não foi possível enviar agora.')}finally{input.disabled=false;input.focus()}}}
async function refresh(){if(!allowed())return;let box=document.getElementById('cg-parent-chat');if(!box){box=document.createElement('section');box.id='cg-parent-chat';box.className='card cg-parent-chat';const home=document.getElementById('home');if(home)home.appendChild(box)}try{renderBox(await load())}catch(e){renderBox(demoMessages())}filterParentViews()}
function installGuard(){if(window.__cgChatGuard)return;const baseRender=window.render;if(typeof baseRender==='function'){window.render=function(){baseRender.apply(this,arguments);setTimeout(function(){filterParentViews();if(allowed())refresh()},0)};window.__cgChatGuard=true}}
function css(){if(document.getElementById('cg-chat-css'))return;const s=document.createElement('style');s.id='cg-chat-css';s.textContent='.cg-parent-chat{margin-top:14px}.cg-chat-list{height:300px;overflow:auto;display:grid;gap:8px;padding:4px 0 10px}.cg-chat-msg{display:flex;justify-content:flex-start}.cg-chat-msg.mine{justify-content:flex-end}.cg-chat-msg>div{max-width:86%;padding:9px 11px;border-radius:14px;background:#f2f4f7}.cg-chat-msg.mine>div{background:#111827;color:#fff}.cg-chat-msg strong{display:block;font-size:10px;margin-bottom:3px}.cg-chat-msg span{display:block;font-size:12px;line-height:1.4;white-space:pre-wrap;word-break:break-word}.cg-chat-msg small{display:block;font-size:9px;opacity:.6;margin-top:4px}.cg-chat-form{display:flex;gap:8px;margin-top:8px}.cg-chat-form input{flex:1;min-width:0;border:1px solid #dfe3e8;border-radius:11px;padding:11px}.cg-chat-form .btn{white-space:nowrap}@media(max-width:600px){.cg-chat-form{align-items:stretch}.cg-chat-form .btn{padding-inline:12px}}';document.head.appendChild(s)}
function boot(){css();installGuard();if(allowed())setTimeout(refresh,120);setInterval(function(){if(allowed()&&document.visibilityState!=='hidden')refresh()},2500);window.addEventListener('storage',function(e){if(e.key===LOCAL||e.key==='cgRole'||e.key==='cgActiveChild')refresh()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
window.ClubGestChat={refresh:refresh,send:send};
})();
