(()=>{'use strict';
const API='/api/chat',LOCAL='clubgest_v3',CHAT_KEY='cgChatMessages';
const DEMO_UIDS={parent:'00000000-0000-0000-0000-000000000001',coach:'00000000-0000-0000-0000-000000000002',admin:'00000000-0000-0000-0000-000000000003'};
const role=()=>localStorage.getItem('cgRole')||'parent';
const allowed=()=>['parent','coach','admin'].includes(role());
const actorUid=()=>window.ClubGestProfile?.uid?.()||DEMO_UIDS[role()]||DEMO_UIDS.parent;
const senderName=()=>window.ClubGestProfile?.name?.()||({parent:'Encarregado',coach:'Treinador',admin:'Administrador'}[role()]||'Membro do clube');
const state=()=>{try{return JSON.parse(localStorage.getItem(LOCAL)||'{}')}catch(e){return{}}};
const localMessages=()=>{const s=state();return Array.isArray(s[CHAT_KEY])?s[CHAT_KEY]:[]};
const esc=v=>String(v??'').replace(/[&<>\\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[m]));
async function load(){try{const r=await fetch(API,{cache:'no-store'});if(!r.ok)throw 0;return await r.json()}catch(e){return localMessages()}}
async function send(body){const clean=String(body||'').trim();if(!clean)return false;const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role:role(),sender:actorUid(),sender_name:senderName(),body:clean})});if(!r.ok)throw new Error('chat '+r.status);return true}
function render(messages){const el=document.getElementById('cg-parent-chat');if(!el)return;const mine=actorUid();el.innerHTML='<div class="head"><div><h2>💬 Chat do clube</h2><p>Online · Encarregados, treinadores e administradores</p></div><span class="badge green">● Online</span></div><div class="cg-chat-list">'+(messages.length?messages.map(m=>'<div class="cg-chat-msg '+(m.sender_profile_id===mine?'mine':'')+'"><div><strong>'+esc(m.sender_name||'Membro do clube')+'</strong><span>'+esc(m.body)+'</span><small>'+new Date(m.created_at).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})+'</small></div></div>').join(''):'<div class="empty">Ainda não há mensagens. Envie a primeira pergunta.</div>')+'</div><form class="cg-chat-form" id="cg-chat-form"><input id="cg-chat-input" maxlength="2000" autocomplete="off" placeholder="Escreva uma pergunta ou mensagem…"><button class="btn red" type="submit">Enviar</button></form>';const list=el.querySelector('.cg-chat-list');list.scrollTop=list.scrollHeight;el.querySelector('#cg-chat-form').onsubmit=async e=>{e.preventDefault();const input=el.querySelector('#cg-chat-input'),v=input.value.trim();if(!v)return;input.disabled=true;try{await send(v);input.value='';await refresh()}catch(err){input.value=v;if(typeof window.toast==='function')window.toast('Não foi possível enviar a mensagem.')}finally{input.disabled=false;input.focus()}}}
async function refresh(){if(!allowed())return;let el=document.getElementById('cg-parent-chat');if(!el){el=document.createElement('section');el.id='cg-parent-chat';el.className='card cg-parent-chat';const home=document.getElementById('home');if(home)home.appendChild(el)}const input=document.getElementById('cg-chat-input');if(input&&document.activeElement===input&&input.value.trim())return;render(await load())}
function css(){if(document.getElementById('cg-chat-css'))return;const s=document.createElement('style');s.id='cg-chat-css';s.textContent='.cg-parent-chat{margin-top:14px}.cg-chat-list{height:300px;overflow:auto;display:grid;gap:8px;padding:4px 0 10px}.cg-chat-msg{display:flex;justify-content:flex-start}.cg-chat-msg.mine{justify-content:flex-end}.cg-chat-msg>div{max-width:86%;padding:9px 11px;border-radius:14px;background:#f2f4f7}.cg-chat-msg.mine>div{background:#111827;color:#fff}.cg-chat-msg strong{display:block;font-size:10px;margin-bottom:3px}.cg-chat-msg span{display:block;font-size:12px;line-height:1.4;white-space:pre-wrap;word-break:break-word}.cg-chat-msg small{display:block;font-size:9px;opacity:.6;margin-top:4px}.cg-chat-form{display:flex;gap:8px;margin-top:8px}.cg-chat-form input{flex:1;min-width:0;border:1px solid #dfe3e8;border-radius:11px;padding:11px}.cg-chat-form .btn{white-space:nowrap}@media(max-width:600px){.cg-chat-form{align-items:stretch}.cg-chat-form .btn{padding-inline:12px}}';document.head.appendChild(s)}function boot(){css();if(allowed())setTimeout(refresh,350);setInterval(()=>{if(allowed()&&document.visibilityState!=='hidden')refresh()},4000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();window.ClubGestChat={refresh,send}})();