(function(){
'use strict';
const K='fcd03-enhance-v1';
function addStyle(){if(document.getElementById(K))return;const s=document.createElement('style');s.id=K;s.textContent=`
.cg-command{margin:0 0 14px;padding:16px;border-radius:20px;background:linear-gradient(135deg,#090909,#1b1b1b);color:#fff;border:1px solid #2d2d2d;box-shadow:0 14px 32px #00000018;display:flex;align-items:center;justify-content:space-between;gap:14px}.cg-command .cg-copy{min-width:0}.cg-command .cg-kicker{font-size:9px;font-weight:900;letter-spacing:.14em;color:#ff6670}.cg-command h2{margin:4px 0 3px;font-size:18px;letter-spacing:-.025em}.cg-command p{margin:0;color:#bdbdbd;font-size:10px}.cg-command .cg-actions{display:flex;gap:7px;flex-wrap:wrap;justify-content:flex-end}.cg-command button{padding:9px 11px;border-radius:10px;background:#e30613;color:#fff;font-size:10px;font-weight:850}.cg-command button.alt{background:#fff;color:#111}.cg-pulse{display:inline-block;width:7px;height:7px;border-radius:50%;background:#e30613;margin-right:5px;box-shadow:0 0 0 4px #e3061322}.cg-section-tag{display:inline-flex;align-items:center;gap:5px;margin-bottom:7px;padding:5px 8px;border-radius:999px;background:#fff0f1;color:#b4000d;font-size:9px;font-weight:900}.cg-statline{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.cg-chip{padding:6px 8px;border-radius:999px;background:#f5f5f5;color:#444;font-size:9px;font-weight:800;border:1px solid #e9e9e9}.cg-chip strong{color:#e30613}.today{position:relative;overflow:hidden}.today:after{content:'FCD03';position:absolute;right:-9px;bottom:-18px;font-size:52px;font-weight:950;letter-spacing:-.08em;color:#e3061308;pointer-events:none}@media(max-width:760px){.cg-command{align-items:flex-start;flex-direction:column}.cg-command .cg-actions{justify-content:flex-start}.cg-command button{flex:1}.cg-command .cg-actions{width:100%}}
`;document.head.appendChild(s)}
function goSafe(id){if(typeof window.go==='function')window.go(id)}
function inject(){addStyle();const home=document.getElementById('home');if(!home||document.getElementById('cg-command'))return;const box=document.createElement('div');box.id='cg-command';box.className='cg-command';box.innerHTML='<div class="cg-copy"><div class="cg-kicker"><span class="cg-pulse"></span>FCD03 · CENTRO DE FORMAÇÃO</div><h2>Clube em movimento.</h2><p>Organiza treinos, equipa e presenças num só lugar.</p><div class="cg-statline"><span class="cg-chip">U7</span><span class="cg-chip">U9</span><span class="cg-chip">U11</span><span class="cg-chip"><strong>●</strong> Sistema online</span></div></div><div class="cg-actions"><button data-go="team">Ver equipa</button><button class="alt" data-go="calendar">Calendário</button></div>';
home.prepend(box);box.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>goSafe(b.dataset.go)))}
function polish(){addStyle();document.querySelectorAll('.section .head h2,.section .head h3').forEach(h=>{if(h.dataset.cgPolished)return;h.dataset.cgPolished='1'});const title=document.querySelector('#home .hero h1');if(title&&title.textContent.trim()===''){title.textContent='Clube em movimento.'}}
function boot(){inject();polish()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();new MutationObserver(()=>{inject();polish()}).observe(document.documentElement,{childList:true,subtree:true});
})();
